<?php

namespace DoctrineORMModule\Proxy\__CG__\Object\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DocumentAttributeCollection extends \Object\Entity\DocumentAttributeCollection implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Object\\Entity\\DocumentAttributeCollection' . "\0" . 'id', '' . "\0" . 'Object\\Entity\\DocumentAttributeCollection' . "\0" . 'attributeTypeCollection', '' . "\0" . 'Object\\Entity\\DocumentAttributeCollection' . "\0" . 'parentDocumentAttribute', '' . "\0" . 'Object\\Entity\\DocumentAttributeCollection' . "\0" . 'cdt', '' . "\0" . 'Object\\Entity\\DocumentAttributeCollection' . "\0" . 'documentAttribute');
        }

        return array('__isInitialized__', '' . "\0" . 'Object\\Entity\\DocumentAttributeCollection' . "\0" . 'id', '' . "\0" . 'Object\\Entity\\DocumentAttributeCollection' . "\0" . 'attributeTypeCollection', '' . "\0" . 'Object\\Entity\\DocumentAttributeCollection' . "\0" . 'parentDocumentAttribute', '' . "\0" . 'Object\\Entity\\DocumentAttributeCollection' . "\0" . 'cdt', '' . "\0" . 'Object\\Entity\\DocumentAttributeCollection' . "\0" . 'documentAttribute');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DocumentAttributeCollection $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttributeTypeCollection(\Object\Entity\AttributeTypeCollection $attributeTypeCollection = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttributeTypeCollection', array($attributeTypeCollection));

        return parent::setAttributeTypeCollection($attributeTypeCollection);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttributeTypeCollection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributeTypeCollection', array());

        return parent::getAttributeTypeCollection();
    }

    /**
     * {@inheritDoc}
     */
    public function setParentDocumentAttribute(\Object\Entity\DocumentAttribute $parentDocumentAttribute = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParentDocumentAttribute', array($parentDocumentAttribute));

        return parent::setParentDocumentAttribute($parentDocumentAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentDocumentAttribute()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentDocumentAttribute', array());

        return parent::getParentDocumentAttribute();
    }

    /**
     * {@inheritDoc}
     */
    public function addCdt(\Object\Entity\CurrentDocumentType $cdt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCdt', array($cdt));

        return parent::addCdt($cdt);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCdt(\Object\Entity\CurrentDocumentType $cdt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCdt', array($cdt));

        return parent::removeCdt($cdt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCdt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCdt', array());

        return parent::getCdt();
    }

    /**
     * {@inheritDoc}
     */
    public function addDocumentAttribute(\Object\Entity\DocumentAttribute $documentAttribute)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDocumentAttribute', array($documentAttribute));

        return parent::addDocumentAttribute($documentAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDocumentAttribute(\Object\Entity\DocumentAttribute $documentAttribute)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDocumentAttribute', array($documentAttribute));

        return parent::removeDocumentAttribute($documentAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumentAttribute()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumentAttribute', array());

        return parent::getDocumentAttribute();
    }

    /**
     * {@inheritDoc}
     */
    public function getAll()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAll', array());

        return parent::getAll();
    }

}
