<?php

namespace DoctrineORMModule\Proxy\__CG__\Object\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MenuClient extends \Object\Entity\MenuClient implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Object\\Entity\\MenuClient' . "\0" . 'id', '' . "\0" . 'Object\\Entity\\MenuClient' . "\0" . 'name', '' . "\0" . 'Object\\Entity\\MenuClient' . "\0" . 'entity', '' . "\0" . 'Object\\Entity\\MenuClient' . "\0" . 'icon', '' . "\0" . 'Object\\Entity\\MenuClient' . "\0" . 'isNotScreen', '' . "\0" . 'Object\\Entity\\MenuClient' . "\0" . 'type', '' . "\0" . 'Object\\Entity\\MenuClient' . "\0" . 'children', '' . "\0" . 'Object\\Entity\\MenuClient' . "\0" . 'parent');
        }

        return array('__isInitialized__', '' . "\0" . 'Object\\Entity\\MenuClient' . "\0" . 'id', '' . "\0" . 'Object\\Entity\\MenuClient' . "\0" . 'name', '' . "\0" . 'Object\\Entity\\MenuClient' . "\0" . 'entity', '' . "\0" . 'Object\\Entity\\MenuClient' . "\0" . 'icon', '' . "\0" . 'Object\\Entity\\MenuClient' . "\0" . 'isNotScreen', '' . "\0" . 'Object\\Entity\\MenuClient' . "\0" . 'type', '' . "\0" . 'Object\\Entity\\MenuClient' . "\0" . 'children', '' . "\0" . 'Object\\Entity\\MenuClient' . "\0" . 'parent');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MenuClient $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntity($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntity', array($entity));

        return parent::setEntity($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntity', array());

        return parent::getEntity();
    }

    /**
     * {@inheritDoc}
     */
    public function setIcon($icon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIcon', array($icon));

        return parent::setIcon($icon);
    }

    /**
     * {@inheritDoc}
     */
    public function getIcon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIcon', array());

        return parent::getIcon();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsNotScreen($isNotScreen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsNotScreen', array($isNotScreen));

        return parent::setIsNotScreen($isNotScreen);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsNotScreen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsNotScreen', array());

        return parent::getIsNotScreen();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(\Object\Entity\MenuClientType $type = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeObj()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeObj', array());

        return parent::getTypeObj();
    }

    /**
     * {@inheritDoc}
     */
    public function setParent(\Object\Entity\MenuClient $parent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', array($parent));

        return parent::setParent($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function getParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParent', array());

        return parent::getParent();
    }

    /**
     * {@inheritDoc}
     */
    public function getParentObj()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentObj', array());

        return parent::getParentObj();
    }

    /**
     * {@inheritDoc}
     */
    public function addChildren(\Doctrine\Common\Collections\Collection $children)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addChildren', array($children));

        return parent::addChildren($children);
    }

    /**
     * {@inheritDoc}
     */
    public function removeChildren(\Doctrine\Common\Collections\Collection $children)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeChildren', array($children));

        return parent::removeChildren($children);
    }

    /**
     * {@inheritDoc}
     */
    public function getChildren()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChildren', array());

        return parent::getChildren();
    }

    /**
     * {@inheritDoc}
     */
    public function getChildrenOutput()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChildrenOutput', array());

        return parent::getChildrenOutput();
    }

    /**
     * {@inheritDoc}
     */
    public function getMenuClientSimple()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMenuClientSimple', array());

        return parent::getMenuClientSimple();
    }

    /**
     * {@inheritDoc}
     */
    public function getAll()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAll', array());

        return parent::getAll();
    }

}
