<html>
<head>
    <meta charset="utf-8">
    <meta name="csrf-token" content="<?php echo $this->layout()->token ?>">
    <meta name="csrf-token23" content="<?php echo $this->layout()->tokenHelper ?>">
    <meta name="csrf-token2" content="<?php echo $this->layout()->tokenHelper2 ?>">
    <meta name="csrf-token3" content="<?php echo $this->layout()->tokenHelper3 ?>">
    <meta name="csrf-token4" content="<?php echo $this->tokenHelper ?>">
    <meta name="csrf-token41" content="<?php echo $this->token_helper ?>">
    <meta name="csrf-token42" content="<?php //echo $this->token_helper->getToken() ?>">
    <meta name="csrf-token43" content="<?php echo $this->tokenHelper3 ?>">
    <title><?php echo 'testTitle'; ?></title>
    <link href="css/bootstrap.min.css" rel="stylesheet" media="all"/>
    <link href="css/bootstrap-responsive.min.css" rel="stylesheet" media="all"/>
    <link href="css/bootstrap-theme.min.css" rel="stylesheet" media="all"/>
    <link href="css/main.css" rel="stylesheet" media="all"/>
</head>
<body>
<?php echo $this->layout()->content ?>
<?php //echo var_dump($this->layout()) ?>
<?php //echo var_dump($this) ?>
<?php echo var_dump($this->layout()->tokenhelper) ?>
<?php echo var_dump($this->tokenhelper) ?>
<?php echo var_dump($this->tokenHelper) ?>
<?php echo var_dump($this->tokenHelper3) ?>
<div id="main_container">
    <div id="header">
        <div id="logo" onclick="window.location.replace('#enter')">Адрес.Ру</div>
        <div id="header_login"></div>
    </div>
    <div id="left_panel"></div>
    <div id="main_window">
        <div id="main_top"></div>
        <div id="main_main"></div>
    </div>
    <div id="global_modal"></div>
    <div class="modal_window"></div>
</div>
<script data-main="js/app/backbone_index" src="js/require.js" type="text/javascript"></script>
</body>
</html>

