<html>
<head>
    <meta charset="utf-8">
    <meta name="csrf-token" content="<?php //echo $this->plugin('token')->getToken(); ?>">
    <title><?php echo 'testTitle'; ?></title>
    <link href="css/font-awesome.min.css" rel="stylesheet" media="all"/>
    <link href="css/bootstrap.min.css" rel="stylesheet" media="all"/>
    <link href="css/bootstrap-responsive.min.css" rel="stylesheet" media="all"/>
    <link href="css/bootstrap-theme.min.css" rel="stylesheet" media="all"/>
    <link href="css/main.css" rel="stylesheet" media="all"/>
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Open Sans">
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Roboto Condensed">
</head>
<body>
<?php $this->plugin('token'); ?>
<div id="main_container">
    <div id="header">
        <div id="logo" onclick="window.location.replace('#enter')">Москит</div>
        <div id="header_login"></div>
    </div>
    <div id="main_row">
        <div id="left_panel"></div>
        <div id="main_window">
            <div id="main_top"></div>
            <div id="main_main"></div>
        </div>
        <div id="right_panel"></div>
    </div>
    <div id="footer"></div>
    <div id="global_modal"></div>
    <div class="modal_window"></div>
</div>
<script data-main="js/app/backbone_index" src="js/require.js" type="text/javascript"></script>
</body>
</html>

