<html>
<head>
    <meta charset="utf-8">
    <title>LAYOUT PHTML</title>
    <link href="css/bootstrap.min.css" rel="stylesheet" media="all"/>
    <link href="css/bootstrap-responsive.min.css" rel="stylesheet" media="all"/>
    <link href="css/bootstrap-theme.min.css" rel="stylesheet" media="all"/>
    <link href="css/main.css" rel="stylesheet" media="all"/>
</head>
<body>
<div id="main_container">
    <div id="header"></div>
    <div id="left_panel"></div>
    <div id="main_window">
        <div id="main_top"></div>
        <div id="main_main"></div>
    </div>
</div>
<script data-main="js/app/backbone_index" src="js/require.js" type="text/javascript"></script>
</body>
</html>

